version: "2"
services:
  desktop:
    image: ghcr.io/taoky/m.a.r.s:master
    environment:
      - DISPLAY=$DISPLAY
      - XAUTHORITY=$XAUTHORITY
      - XDG_RUNTIME_DIR=/run/user/1000/
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:$XAUTHORITY
      - /run/user/1000/pipewire-0:/run/user/1000/pipewire-0
      - $HOME/.config/marsshooter:/home/marsshooter/.config/marsshooter
      - /dev/dri:/dev/dri
