#!/bin/bash
# Generated by GPT-4
# 校验参数
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <efficiency-only|normal|no-efficiency>"
    exit 1
fi

# 根据参数关闭或启用 CPU 核心
case $1 in
    efficiency-only)
        # 关闭 cpu1-7
        for i in {1..7}
        do
            echo "Disabling CPU$i..."
            echo 0 | sudo tee /sys/devices/system/cpu/cpu$i/online
        done
        ;;
    normal)
        # 打开所有 CPU
        for i in {1..15}
        do
            echo "Enabling CPU$i..."
            echo 1 | sudo tee /sys/devices/system/cpu/cpu$i/online
        done
        ;;
    no-efficiency)
        # 关闭 cpu8-15
        for i in {8..15}
        do
            echo "Disabling CPU$i..."
            echo 0 | sudo tee /sys/devices/system/cpu/cpu$i/online
        done
        ;;
    *)
        echo "Invalid argument: $1"
        echo "Usage: $0 <efficiency-only|normal|no-efficiency>"
        exit 2
        ;;
esac

echo "Operation completed."

