# https://github.com/taoky/cargo-blocklist
paths = ["/home/taoky/Projects/cargo-blocklist/"]

[source.crates-io]
replace-with = 'ustc'

[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

[registries.ustc]
index = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

