services:
  shell:
    build: .
    volumes:
      # replace this to your own dir
      - /home/taoky/iOSBackup:/backup
      # usbmuxd will recreate /run/usbmuxd when reconnected
      # so let's just mount /run as a whole
      - /run/:/run/
