AMDCPU = {"amd-ucode"}

INTELCPU = {"intel-ucode"}

AMDGPU = {
    "llama.cpp-hip",
}

INTELGPU = {
    "intel-gpu-tools",
    "vulkan-intel",
}

TUNED = {
    "tuned",
    "tuned-ppd",
}

TLP = {"tlp"}

APFS = {
    "apfs-fuse-git",
}

NIRI = {
    "niri",
    "xwayland-satellite",
    "swaybg",
    "swayidle",
    "swaylock",
}

ICEPINYIN = {
    "fcitx5-rime",
    "rime-ice-pinyin-git",
    "rime-pinyin-moegirl",
    "rime-pinyin-zhwiki",
}

WLAN_FALLBACK = {
    "iw",
    "iwd",
}

STEAM_HOST = {
    "steam",
}

LOGITECH = {
    "piper",
}

COMMON = {
    "1password",
    "1password-cli",
    "aegisub",
    "anki",
    "apparmor",
    "archlinuxcn-keyring",
    "audacity",
    "autocorrect-bin",
    "base",
    "base-devel",
    "bat",
    "bcc",
    "bcc-libbpf-tools",
    "bear",
    "bind",
    "bluez-utils",
    "bmon",
    "btrfs-progs",
    "bustle",
    "bpftrace",
    "cargo-deb",
    "cargo-edit",
    "cargo-release",
    "chafa",
    "cheese",
    "chromium",
    "clang",
    "claude-code",
    "cpio",
    "dconf-editor",
    "devtools",
    "digikam",
    "direnv",
    "dmidecode",
    "dnsmasq",
    "dotnet-sdk",
    "dpkg",
    "efibootmgr",
    "esbuild",
    "eslint",
    "evtest",
    "extension-manager",
    "eza",
    "fastfetch",
    "fcitx5",
    "fcitx5-chinese-addons",
    "fcitx5-configtool",
    "fcitx5-gtk",
    "fcitx5-mozc",
    "fcitx5-pinyin-moegirl",
    "fcitx5-pinyin-zhwiki",
    "fcitx5-qt",
    "fd",
    "file-roller",
    "filezilla",
    "fio",
    "firefox",
    "firefoxpwa",
    "fish",
    "flatpak",
    "flatpak-builder",
    "fwupd",
    "fx",
    "gcc",
    "gdb",
    "gdm",
    "gimp",
    "git",
    "git-delta",
    "git-keeper-git",
    "git-lfs",
    "github-cli",
    "glib2-devel",
    "gnome-backgrounds",
    "gnome-calculator",
    "gnome-calendar",
    "gnome-control-center",
    "gnome-font-viewer",
    "gnome-keyring",
    "gnome-session",
    "gnome-shell",
    "gnome-shell-debug",
    "gnome-shell-docs",
    "gnome-shell-extensions",
    "gnome-system-monitor",
    "gnome-tweaks",
    "gnome-weather",
    "go",
    "golangci-lint",
    "goreleaser",
    "gparted",
    "grub",
    "gst-plugin-pipewire",
    "gtk3-demos",
    "gtk4-demos",
    "gvfs-nfs",
    "gvfs-onedrive",
    "handbrake-cli",
    "htop",
    "ibus",
    "iftop",
    "inxi",
    "iotop-c",
    "jq",
    "kate",
    "kcharselect",
    "kolourpaint",
    "krita",
    "less",
    "libreoffice-fresh",
    "linux",
    "linux-firmware",
    "localsend",
    "lollypop",
    "loupe",
    "luminance",
    "man-db",
    "man-pages",
    "markdownlint-cli2",
    "meson",
    "moreutils",
    "mpv",
    "mpv-mpris",
    "mpv-osc-modern-git",
    "mpv-osc-thumbfast-git",
    "mtr",
    "mutter",
    "mutter-debug",
    "mutter-devkit",
    "mutter-docs",
    "mypy",
    "nali-go",
    "namcap",
    "nano",
    "nautilus-open-any-terminal",
    "ncdu",
    "net-tools",
    "netease-cloud-music-gtk4",
    "networkmanager",
    "networkmanager-openvpn",
    "nginx",
    "noto-cjk-ui-patched",
    "noto-fonts-emoji",
    "nvtop",
    "openbsd-netcat",
    "openssh",
    "openvpn",
    "osv-scanner",
    "pandoc-bin",
    "pango-taoky",
    "pango-taoky-debug",
    "pango-taoky-docs",
    "papers",
    "paru",
    "playerctl",
    "pnpm",
    "podman",
    "powertop",
    "pre-commit",
    "prettier",
    "ptyxis-taoky",
    "ptyxis-taoky-debug",
    "pwndbg",
    "pyright",
    "python-bcc",
    "python-biliass",
    "python-keyring",
    "python-tabulate",
    "python-weasyprint",
    "pv",
    "qbittorrent",
    "qemu-full",
    "qemu-user-static-binfmt",
    "qt6-tools",
    "qt6-wayland",
    "rapid-photo-downloader",
    "rasdaemon",
    "ripgrep",
    "ripgrep-all",
    "rsync",
    "ruby-bundler",
    "ruby-erb",
    "ruff",
    "rustscan",
    "rustup",
    "shellcheck-static",
    "shfmt",
    "showmethekey",
    "sqlitebrowser",
    "strace",
    "sudo",
    "supertuxkart",
    "sushi",
    "syncthing",
    "tealdeer",
    "teamspeak3",
    "tigervnc",
    "tmux",
    "tokei",
    "tree",
    "ttf-jetbrains-mono",
    "ttf-liberation",
    "ttf-lxgw-wenkai",
    "typescript",
    "uv",
    "vala",
    "vim",
    "virt-manager",
    "virt-viewer",
    "visual-studio-code-bin",
    "w3m",
    "waycheck",
    "weston",
    "whois",
    "wireguard-tools",
    "wireless-regdb",
    "wireshark-qt",
    "wl-clipboard",
    "xorg-server-xephyr",
    "xorg-xdpyinfo",
    "xorg-xeyes",
    "xorg-xinput",
    "xorg-xlsclients",
    "xterm",
    "xungu-git",
    "xwayland-run",
    "yt-dlp",
    "zerotier-one",
}

NANOKA = AMDCPU | AMDGPU | TUNED | COMMON | NIRI | WLAN_FALLBACK | STEAM_HOST | LOGITECH
SHIMARIN = INTELCPU | INTELGPU | TLP | APFS | COMMON | NIRI | ICEPINYIN | LOGITECH

packages = {
    "nanoka.taoky.moe": NANOKA,
    "shimarin.taoky.moe": SHIMARIN,
}
