COMMON = {
    "app.drey.EarTag",
    "com.belmoussaoui.Decoder",
    "com.belmoussaoui.ashpd.demo",
    "com.dec05eba.gpu_screen_recorder",
    "com.github.finefindus.eyedropper",
    "com.github.huluti.Curtail",
    "com.github.jeromerobert.pdfarranger",
    "com.github.tchx84.Flatseal",
    "com.mikeasoft.pied",
    "com.qq.QQ",
    "com.rafaelmardojai.Blanket",
    "com.tencent.WeChat",
    "com.tencent.wemeet",
    "com.usebottles.bottles",
    "dev.filimonov.klogg",
    "info.febvre.Komikku",
    "io.github.flattool.Warehouse",
    "io.github.kolunmi.Bazaar",
    "io.github.waylyrics.Waylyrics",
    "io.missioncenter.MissionCenter",
    "me.kavishdevar.librepods",
    "moe.taoky.clicking-circles-player",
    "moe.tsuna.tsukimi",
    "net.sapples.LiveCaptions",
    "net.werwolv.ImHex",
    "org.gnome.Papers",
    "org.gnome.design.IconLibrary",
    "org.gnome.dspy",
    "org.kde.krita",
    "org.mozilla.Thunderbird",
    "org.rncbc.qpwgraph",
    "org.telegram.desktop",
    "sh.cider.Cider",
    "sh.ppy.osu",
}

packages = {
    "nanoka.taoky.moe": COMMON,
    "shimarin.taoky.moe": COMMON,
}
